<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Commands\Login\" />
    <Folder Include="Features\Auth\Commands\RefreshToken\" />
    <Folder Include="Features\Auth\Commands\RevokeToken\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Books\Commands\Delete\" />
    <Folder Include="Features\Books\Commands\Update\" />
    <Folder Include="Features\Books\DTOs\" />
    <Folder Include="Features\Books\Queries\GetById\" />
    <Folder Include="Features\Books\Queries\GetAll\" />
    <Folder Include="Common\Constants\" />
    <Folder Include="Features\BookCategories\" />
    <Folder Include="Features\Books\Queries\SearchBooks\" />
    <Folder Include="Features\Orders\" />
    <Folder Include="Features\Users\Commands\UpdateProfile\" />
    <Folder Include="Features\Users\Queries\GetCurrentUser\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookStore.Domain\BookStore.Domain.csproj" />
  </ItemGroup>

</Project>
