<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Books\Commands\Delete\" />
    <Folder Include="Books\Commands\Update\" />
    <Folder Include="Books\Queries\GetById\" />
    <Folder Include="Books\Queries\GetAll\" />
    <Folder Include="Common\Behavious\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Mappings\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookStore.Domain\BookStore.Domain.csproj" />
  </ItemGroup>

</Project>
