<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\Constants\**" />
    <Compile Remove="Features\Auth\Commands\RevokeToken\**" />
    <Compile Remove="Features\Auth\Queries\**" />
    <Compile Remove="Features\BookCategories\**" />
    <Compile Remove="Features\Users\Commands\UpdateProfile\**" />
    <Compile Remove="Features\Users\Queries\GetCurrentUser\**" />
    <EmbeddedResource Remove="Common\Constants\**" />
    <EmbeddedResource Remove="Features\Auth\Commands\RevokeToken\**" />
    <EmbeddedResource Remove="Features\Auth\Queries\**" />
    <EmbeddedResource Remove="Features\BookCategories\**" />
    <EmbeddedResource Remove="Features\Users\Commands\UpdateProfile\**" />
    <EmbeddedResource Remove="Features\Users\Queries\GetCurrentUser\**" />
    <None Remove="Common\Constants\**" />
    <None Remove="Features\Auth\Commands\RevokeToken\**" />
    <None Remove="Features\Auth\Queries\**" />
    <None Remove="Features\BookCategories\**" />
    <None Remove="Features\Users\Commands\UpdateProfile\**" />
    <None Remove="Features\Users\Queries\GetCurrentUser\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Categories\Commands\" />
    <Folder Include="Features\Categories\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookStore.Domain\FixHub.Domain.csproj" />
  </ItemGroup>

</Project>
